all:
	gcc -Wall -g p1.c -o p1
	gcc -Wall -g p2.c -o p2
	gcc -Wall -g p3.c -o p3
	gcc -Wall -g p4.c -o p4
	gcc -Wall -g p5.c -o p5
	gcc -Wall -g p6.c -o p6
	gcc -Wall -g p7.c -o p7
	gcc -Wall -g p8.c -o p8
	gcc -Wall -g p9.c -o p9
	gcc -Wall -g p10.c -o p10
	